import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import './globals.css';
import React, { JSX } from 'react';
import { Footer, Header, Sidebar } from '@/layout';
import styles from './layout.module.css';

const notoSans = Noto_Sans({
  subsets: ['cyrillic', 'latin'],
  weight: ['300', '400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'MyTop - наш лучший топ',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element => (
  <html lang="ru" className={notoSans.className}>
    <body className={styles.wrapper}>
      <Header className={styles.header} />
      <Sidebar className={styles.sidebar} />
      <main className={styles.main}>{children}</main>
      <Footer className={styles.footer} />
    </body>
  </html>
);

export default RootLayout;
