import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import './globals.css';
import React, { JSX } from 'react';

const notoSans = Noto_Sans({
  subsets: ['cyrillic', 'latin'],
  weight: ['300', '400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'MyTop - наш лучший топ',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element => (
  <html lang="ru">
    <body className={notoSans.className}>{children}</body>
  </html>
);

export default RootLayout;
